[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
a1 = "7WpuY6r6vwyfsmxbkhBxB7Nxzg7szk39qG8JJDP9mvFo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./pee/wallet_1.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
