[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
a3 = "AW5Swy7B8vcL9HSNb3HcErMoKPgthb41FhLEWCZB4wqA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./pee/"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
