[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
a3 = "GaRvgs1GokWXUFpHbB83w5tYQCunnFmk6eUozyBfuJhN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./pee/wallet_1.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
